apiVersion: devopstoolkit.live/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: vfarcic-silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    image: ghcr.io/vfarcic/idp-full-demo
    tag: 0.0.5
    port: 8080
    host: vfarcic.silly-demo.35.231.186.105.nip.io
    ingressClassName: contour
    db:
      secret: silly-demo-db
      storeName: google
      name: main
