apiVersion: devopstoolkit.live/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    image: ghcr.io/vfarcic/idp-full-demo
    tag: 0.0.7
    port: 8080
    host: staging.silly-demo.209.94.57.140.nip.io
    ingressClassName: contour
    db:
      secret: silly-demo-db
      name: main
