apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
  labels:
    app-owner: vfarcic
spec:
  id: silly-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: a-team
    image: ghcr.io/vfarcic/idp-full-demo:0.0.17
    tag: FIXME
    port: 8080
    host: silly-demo.127.0.0.1.nip.io
    ingressClassName: nginx
    db:
      secret: silly-demo-db
    repository:
      enabled: true
      name: idp-full-app
    ci:
      enabled: true
